name: ongkos_kirim_getx_10_mar
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_search: ^2.0.1
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  get: ^4.6.1
  get_storage: ^2.0.3
  http: ^0.13.4

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
flutter:
  assets:
    - assets/
    - assets/icon.png
  uses-material-design: true
